# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_randnum_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='randnum',
            name='rand_list',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
