# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_auto_20171203_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='randnum',
            name='fact',
            field=models.CharField(default=0, max_length=1000000),
            preserve_default=False,
        ),
    ]
