# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_randnum_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randnum',
            name='fact',
        ),
    ]
